import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    app_name: 'AMR-Guard',
    tagline: 'Secure Disposal. Stronger Medicine.',
    welcome_subtitle: 'Scan your medications, check their environmental hazard, and find the nearest SafeDrop Pharmacy — no login required.',
    select_language: 'Select Language',
    get_started: 'Get Started',
    home: 'Home',
    scan: 'Scan',
    map: 'Map',
    profile: 'Guardian',
    recent_scans: 'Recent Scans',
    quick_actions: 'Quick Actions',
    scan_medication: 'Snap & Report',
    find_centres: 'SafeDrop Map',
    learn_amr: 'AMR Knowledge',
    total_scans: 'Total Scans',
    antibiotics_found: 'Antibiotics Found',
    disposed_safely: 'Disposed Safely',
    offline_banner: 'You are offline. Scans will sync when connection is restored.',
    camera_permission: 'Camera permission is required to scan medications.',
    capture: 'Capture',
    analyzing: 'Analyzing medication...',
    result_title: 'Analysis Result',
    drug_detected: 'Detected',
    confidence: 'Confidence',
    expiry: 'Expiry Status',
    disposal_advice: 'Disposal Recommendation',
    find_nearest: 'Find Nearest SafeDrop Pharmacy',
    scan_another: 'Scan Another',
    saved_offline: 'Saved offline. Will sync when connection is restored.',
    nearest_centres: 'SafeDrop Pharmacies Nearby',
    distance: 'Distance',
    accepts: 'Accepts',
    get_directions: 'Get Directions',
    your_location: 'Your Location',
    loading_map: 'Loading map...',
    locating: 'Getting your location...',
    guardian_level: 'Guardian Level',
    eco_hazard: 'Eco-Hazard Score',
    eco_hazard_info: 'Environmental Impact',
    hazard_high: 'High Risk',
    hazard_medium: 'Medium Risk',
    hazard_low: 'Low Risk',
    // Guardian Tiers
    scout: 'Scout',
    sentinel: 'Sentinel',
    amr_guardian: 'AMR-Guardian',
    scout_desc: 'First disposal reported',
    sentinel_desc: '5 strips safely disposed',
    guardian_desc: 'Consistent monthly disposal + 3 referrals',
    tier_locked: 'Locked',
    tier_unlocked: 'Achieved',
    // Leaderboard
    leaderboard: 'Maha-Leaderboard',
    leaderboard_subtitle: 'City-wise safe disposal competition',
    disposals: 'Disposals',
    guardians: 'Guardians',
    // Knowledge
    knowledge_capsules: 'Knowledge Capsules',
    knowledge_what_title: 'What is AMR?',
    knowledge_what_body: 'Antimicrobial Resistance (AMR) happens when bacteria evolve to resist antibiotics. Improper disposal of antibiotics accelerates this process, making common infections harder to treat.',
    knowledge_why_title: 'Why Safe Disposal?',
    knowledge_why_body: 'When antibiotics enter water systems through flushing or landfills, they create conditions for superbugs. SafeDrop Pharmacies ensure proper incineration, preventing environmental contamination.',
    knowledge_how_title: 'How You Help',
    knowledge_how_body: 'Every strip you bring to a SafeDrop Pharmacy is one less source of contamination. As an AMR Guardian, you directly protect your community from drug-resistant infections.',
    stats: 'Your Impact',
    no_scans_yet: 'No scans yet. Tap "Scan" to get started!',
    antibiotic: 'Antibiotic',
    general: 'General',
    safe_drop_pharmacy: 'SafeDrop Pharmacy',
    govt_health_center: 'Govt. Health Center',
    device_token: 'Device Token',
    device_token_info: 'Anonymous ID — no login required',
    qr_code: 'Disposal QR Code',
    qr_code_info: 'Show this at the SafeDrop Pharmacy to verify your disposal',
    points: 'Points',
    report_disposal: 'Report Disposal',
    about: 'About',
    about_title: 'Why Safe Disposal?',
    about_subtitle: 'Understanding the AMR crisis in India',
    about_hero_title: 'India faces a silent health crisis',
    about_hero_body: 'India is one of the largest consumers of antibiotics in the world. When unused or expired antibiotics are flushed down toilets or thrown in dustbins, they enter our rivers, soil, and groundwater — breeding superbugs that resist all known medicines.',
    about_amr_title: 'What is Antimicrobial Resistance?',
    about_amr_body: 'AMR occurs when bacteria, viruses, and fungi evolve to resist the drugs designed to kill them. This makes common infections like TB, pneumonia, and UTIs much harder — and sometimes impossible — to treat. The WHO calls it one of the top 10 global public health threats.',
    about_why_title: 'Why Does Improper Disposal Matter?',
    about_why_body: 'When antibiotics enter water bodies through household waste, they create low-concentration antibiotic environments. Bacteria in these environments develop resistance genes, creating superbugs. Studies have found antibiotic residues in 80% of Indian rivers tested.',
    about_env_title: 'Environmental Impact',
    about_env_body: 'Pharmaceutical pollution affects aquatic ecosystems, contaminates drinking water sources, and enters the food chain through agriculture. A single improperly disposed antibiotic strip can contaminate thousands of litres of water.',
    about_how_title: 'How SafeDrop Pharmacies Work',
    about_how_body: 'SafeDrop Pharmacies and Government Health Centers collect unused medications and send them for proper incineration at licensed biomedical waste facilities. This ensures zero leaching into the environment and breaks the cycle of resistance.',
    about_you_title: 'Your Role as an AMR Guardian',
    about_you_body: 'Every citizen who brings unused medications to a SafeDrop point becomes a guardian against AMR. By scanning, reporting, and safely disposing, you directly protect your family, community, and future generations from drug-resistant infections.',
    about_tips_title: 'Safe Disposal Tips',
    about_tip_1: 'Never flush medicines down the toilet or sink — they enter the water supply.',
    about_tip_2: 'Do not throw medicines in regular household dustbins — ragpickers and animals are at risk.',
    about_tip_3: 'Check expiry dates regularly and bring expired medicines to a SafeDrop Pharmacy.',
    about_tip_4: 'Complete your full course of antibiotics — do not save leftover doses.',
    about_tip_5: 'Spread awareness — tell your family and neighbours about safe disposal.',
    about_cta: 'Be the change. Scan. Drop. Protect.',
    about_cta_sub: 'Every strip you safely dispose makes India stronger against superbugs.',
  },
  mr: {
    app_name: 'AMR-गार्ड',
    tagline: 'सुरक्षित विल्हेवाट. मजबूत औषध.',
    welcome_subtitle: 'तुमची औषधे स्कॅन करा, त्यांचा पर्यावरणीय धोका तपासा, आणि जवळचे SafeDrop फार्मसी शोधा — लॉगिन आवश्यक नाही.',
    select_language: 'भाषा निवडा',
    get_started: 'सुरू करा',
    home: 'होम',
    scan: 'स्कॅन',
    map: 'नकाशा',
    profile: 'गार्डियन',
    recent_scans: 'अलीकडील स्कॅन',
    quick_actions: 'जलद क्रिया',
    scan_medication: 'स्नॅप आणि रिपोर्ट',
    find_centres: 'SafeDrop नकाशा',
    learn_amr: 'AMR माहिती',
    total_scans: 'एकूण स्कॅन',
    antibiotics_found: 'प्रतिजैविके सापडली',
    disposed_safely: 'सुरक्षित विल्हेवाट',
    offline_banner: 'तुम्ही ऑफलाइन आहात. कनेक्शन आल्यावर स्कॅन सिंक होतील.',
    camera_permission: 'औषधे स्कॅन करण्यासाठी कॅमेरा परवानगी आवश्यक आहे.',
    capture: 'कॅप्चर',
    analyzing: 'औषध विश्लेषण करत आहे...',
    result_title: 'विश्लेषण निकाल',
    drug_detected: 'शोधले',
    confidence: 'आत्मविश्वास',
    expiry: 'कालबाह्यता',
    disposal_advice: 'विल्हेवाट शिफारस',
    find_nearest: 'जवळचे SafeDrop फार्मसी शोधा',
    scan_another: 'दुसरे स्कॅन करा',
    saved_offline: 'ऑफलाइन सेव्ह केले. कनेक्शन आल्यावर सिंक होईल.',
    nearest_centres: 'जवळची SafeDrop फार्मसी',
    distance: 'अंतर',
    accepts: 'स्वीकारते',
    get_directions: 'दिशा मिळवा',
    your_location: 'तुमचे ठिकाण',
    loading_map: 'नकाशा लोड होत आहे...',
    locating: 'तुमचे ठिकाण शोधत आहे...',
    guardian_level: 'गार्डियन स्तर',
    eco_hazard: 'इको-हॅझर्ड स्कोर',
    eco_hazard_info: 'पर्यावरणीय प्रभाव',
    hazard_high: 'उच्च धोका',
    hazard_medium: 'मध्यम धोका',
    hazard_low: 'कमी धोका',
    scout: 'स्काउट',
    sentinel: 'सेंटिनेल',
    amr_guardian: 'AMR-गार्डियन',
    scout_desc: 'पहिली विल्हेवाट नोंदवली',
    sentinel_desc: '५ पट्ट्यांची सुरक्षित विल्हेवाट',
    guardian_desc: 'मासिक विल्हेवाट + ३ रेफरल',
    tier_locked: 'लॉक',
    tier_unlocked: 'प्राप्त',
    leaderboard: 'महा-लीडरबोर्ड',
    leaderboard_subtitle: 'शहरनिहाय सुरक्षित विल्हेवाट स्पर्धा',
    disposals: 'विल्हेवाट',
    guardians: 'गार्डियन',
    knowledge_capsules: 'माहिती कॅप्सूल',
    knowledge_what_title: 'AMR म्हणजे काय?',
    knowledge_what_body: 'प्रतिजैविक प्रतिरोध (AMR) तेव्हा होतो जेव्हा जीवाणू प्रतिजैविकांचा प्रतिकार करण्यासाठी विकसित होतात. प्रतिजैविकांची अयोग्य विल्हेवाट ही प्रक्रिया गतिमान करते.',
    knowledge_why_title: 'सुरक्षित विल्हेवाट का?',
    knowledge_why_body: 'प्रतिजैविके पाण्यात गेल्यास सुपरबग तयार होतात. SafeDrop फार्मसी योग्य भस्मीकरण सुनिश्चित करतात.',
    knowledge_how_title: 'तुम्ही कसे मदत करता',
    knowledge_how_body: 'तुम्ही SafeDrop फार्मसीत आणलेली प्रत्येक पट्टी दूषणाचा एक कमी स्रोत आहे.',
    stats: 'तुमचा प्रभाव',
    no_scans_yet: 'अजून स्कॅन नाही. सुरू करण्यासाठी "स्कॅन" वर टॅप करा!',
    antibiotic: 'प्रतिजैविक',
    general: 'सामान्य',
    safe_drop_pharmacy: 'SafeDrop फार्मसी',
    govt_health_center: 'सरकारी आरोग्य केंद्र',
    device_token: 'डिव्हाइस टोकन',
    device_token_info: 'अनामित ID — लॉगिन आवश्यक नाही',
    qr_code: 'विल्हेवाट QR कोड',
    qr_code_info: 'विल्हेवाट सत्यापित करण्यासाठी SafeDrop फार्मसीमध्ये दाखवा',
    points: 'पॉइंट्स',
    report_disposal: 'विल्हेवाट नोंदवा',
    about: 'माहिती',
    about_title: 'सुरक्षित विल्हेवाट का?',
    about_subtitle: 'भारतातील AMR संकट समजून घेणे',
    about_hero_title: 'भारत एका शांत आरोग्य संकटाला तोंड देत आहे',
    about_hero_body: 'भारत जगातील सर्वात मोठ्या प्रतिजैविक वापरकर्त्यांपैकी एक आहे. जेव्हा न वापरलेली किंवा कालबाह्य प्रतिजैविके शौचालयात फ्लश केली जातात किंवा कचऱ्यात टाकली जातात, तेव्हा ती आमच्या नद्या, माती आणि भूजलात प्रवेश करतात.',
    about_amr_title: 'प्रतिजैविक प्रतिरोध (AMR) म्हणजे काय?',
    about_amr_body: 'AMR तेव्हा होतो जेव्हा जीवाणू, विषाणू आणि बुरशी त्यांना मारण्यासाठी तयार केलेल्या औषधांचा प्रतिकार करण्यासाठी विकसित होतात. यामुळे TB, न्यूमोनिया आणि UTI सारखे सामान्य संक्रमण उपचार करणे कठीण होते.',
    about_why_title: 'अयोग्य विल्हेवाट का महत्त्वाची आहे?',
    about_why_body: 'जेव्हा प्रतिजैविके घरगुती कचऱ्यातून पाण्यात प्रवेश करतात, तेव्हा ती सुपरबग तयार करतात. भारतीय नद्यांच्या 80% चाचण्यांमध्ये प्रतिजैविक अवशेष आढळले.',
    about_env_title: 'पर्यावरणीय प्रभाव',
    about_env_body: 'औषधी प्रदूषणामुळे जलचर परिसंस्था प्रभावित होतात, पिण्याच्या पाण्याचे स्रोत दूषित होतात. एक अयोग्यरित्या टाकलेली प्रतिजैविक पट्टी हजारो लिटर पाणी दूषित करू शकते.',
    about_how_title: 'SafeDrop फार्मसी कसे काम करतात',
    about_how_body: 'SafeDrop फार्मसी आणि सरकारी आरोग्य केंद्रे न वापरलेली औषधे गोळा करतात आणि योग्य भस्मीकरणासाठी पाठवतात.',
    about_you_title: 'AMR गार्डियन म्हणून तुमची भूमिका',
    about_you_body: 'SafeDrop पॉइंटवर न वापरलेली औषधे आणणारा प्रत्येक नागरिक AMR विरुद्ध रक्षक बनतो.',
    about_tips_title: 'सुरक्षित विल्हेवाट टिप्स',
    about_tip_1: 'कधीही शौचालयात औषधे फ्लश करू नका — ती पाणी पुरवठ्यात प्रवेश करतात.',
    about_tip_2: 'सामान्य कचराकुंडीत औषधे टाकू नका — कचरा वेचक आणि प्राण्यांना धोका आहे.',
    about_tip_3: 'कालबाह्यता तारखा नियमित तपासा आणि कालबाह्य औषधे SafeDrop फार्मसीत आणा.',
    about_tip_4: 'प्रतिजैविकांचा संपूर्ण कोर्स पूर्ण करा — उरलेले डोस साठवू नका.',
    about_tip_5: 'जागरूकता पसरवा — तुमच्या कुटुंबाला आणि शेजाऱ्यांना सुरक्षित विल्हेवाटबद्दल सांगा.',
    about_cta: 'बदल घडवा. स्कॅन करा. ड्रॉप करा. रक्षण करा.',
    about_cta_sub: 'तुम्ही सुरक्षितपणे विल्हेवाट लावलेली प्रत्येक पट्टी भारताला सुपरबग्सविरुद्ध मजबूत करते.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('amr-guard-lang') || 'en');
  useEffect(() => { localStorage.setItem('amr-guard-lang', lang); }, [lang]);
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
