import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    app_name: 'AMR-Guard',
    tagline: 'Secure Disposal, Stronger Nation',
    welcome_subtitle: 'Scan your medications, check their environmental hazard, and find the nearest SafeDrop Pharmacy — no login required.',
    select_language: 'Select Language',
    get_started: 'Get Started',
    home: 'Home',
    scan: 'Scan',
    map: 'Map',
    profile: 'Guardian',
    takeback: 'Take-Back',
    request_takeback: 'Request Take-Back',
    recent_scans: 'Recent Scans',
    quick_actions: 'Quick Actions',
    scan_medication: 'Snap & Report',
    find_centres: 'SafeDrop Map',
    learn_amr: 'AMR Knowledge',
    total_scans: 'Total Scans',
    antibiotics_found: 'Antibiotics Found',
    disposed_safely: 'Disposed Safely',
    offline_banner: 'You are offline. Scans will sync when connection is restored.',
    camera_permission: 'Camera permission is required to scan medications.',
    capture: 'Capture',
    analyzing: 'Analyzing medication...',
    result_title: 'Analysis Result',
    drug_detected: 'Detected',
    confidence: 'Confidence',
    expiry: 'Expiry Status',
    disposal_advice: 'Disposal Recommendation',
    find_nearest: 'Find Nearest SafeDrop Pharmacy',
    scan_another: 'Scan Another',
    saved_offline: 'Saved offline. Will sync when connection is restored.',
    nearest_centres: 'SafeDrop Pharmacies Nearby',
    distance: 'Distance',
    accepts: 'Accepts',
    get_directions: 'Get Directions',
    your_location: 'Your Location',
    loading_map: 'Loading map...',
    locating: 'Getting your location...',
    guardian_level: 'Guardian Level',
    eco_hazard: 'Eco-Hazard Score',
    eco_hazard_info: 'Environmental Impact',
    hazard_high: 'High Risk',
    hazard_medium: 'Medium Risk',
    hazard_low: 'Low Risk',
    // Guardian Tiers
    scout: 'Scout',
    sentinel: 'Sentinel',
    amr_guardian: 'AMR-Guardian',
    maha_guardian: 'Maha Guardian',
    scout_desc: 'First disposal reported',
    sentinel_desc: '5 strips safely disposed',
    guardian_desc: 'Consistent monthly disposal + 3 referrals',
    tier_locked: 'Locked',
    tier_unlocked: 'Achieved',
    // Leaderboard
    leaderboard: 'Maha-Leaderboard',
    leaderboard_subtitle: 'City-wise safe disposal competition',
    disposals: 'Disposals',
    guardians: 'Guardians',
    // Knowledge
    knowledge_capsules: 'Knowledge Capsules',
    knowledge_what_title: 'What is AMR?',
    knowledge_what_body: 'Antimicrobial Resistance (AMR) happens when bacteria evolve to resist antibiotics. Improper disposal of antibiotics accelerates this process, making common infections harder to treat.',
    knowledge_why_title: 'Why Safe Disposal?',
    knowledge_why_body: 'When antibiotics enter water systems through flushing or landfills, they create conditions for superbugs. SafeDrop Pharmacies ensure proper incineration, preventing environmental contamination.',
    knowledge_how_title: 'How You Help',
    knowledge_how_body: 'Every strip you bring to a SafeDrop Pharmacy is one less source of contamination. As an AMR Guardian, you directly protect your community from drug-resistant infections.',
    stats: 'Your Impact',
    no_scans_yet: 'No scans yet. Tap "Scan" to get started!',
    antibiotic: 'Antibiotic',
    general: 'General',
    safe_drop_pharmacy: 'SafeDrop Pharmacy',
    govt_health_center: 'Govt. Health Center',
    device_token: 'Device Token',
    device_token_info: 'Anonymous ID — no login required',
    qr_code: 'Disposal QR Code',
    qr_code_info: 'Show this at the SafeDrop Pharmacy to verify your disposal',
    points: 'Points',
    points_earned_today: 'Points Earned Today',
    redeem_points: 'Redeem Points',
    badges: 'Badges',
    rewards_wallet: 'Rewards Wallet',
    transaction_history: 'Transaction History',
    report_disposal: 'Report Disposal',
    about: 'About',
    about_title: 'Why Safe Disposal?',
    about_subtitle: 'Understanding the AMR crisis in India',
    about_hero_title: 'India faces a silent health crisis',
    about_hero_body: 'India is one of the largest consumers of antibiotics in the world. When unused or expired antibiotics are flushed down toilets or thrown in dustbins, they enter our rivers, soil, and groundwater — breeding superbugs that resist all known medicines.',
    about_amr_title: 'What is Antimicrobial Resistance?',
    about_amr_body: 'AMR occurs when bacteria, viruses, and fungi evolve to resist the drugs designed to kill them. This makes common infections like TB, pneumonia, and UTIs much harder — and sometimes impossible — to treat. The WHO calls it one of the top 10 global public health threats.',
    about_why_title: 'Why Does Improper Disposal Matter?',
    about_why_body: 'When antibiotics enter water bodies through household waste, they create low-concentration antibiotic environments. Bacteria in these environments develop resistance genes, creating superbugs. Studies have found antibiotic residues in 80% of Indian rivers tested.',
    about_env_title: 'Environmental Impact',
    about_env_body: 'Pharmaceutical pollution affects aquatic ecosystems, contaminates drinking water sources, and enters the food chain through agriculture. A single improperly disposed antibiotic strip can contaminate thousands of litres of water.',
    about_how_title: 'How SafeDrop Pharmacies Work',
    about_how_body: 'SafeDrop Pharmacies and Government Health Centers collect unused medications and send them for proper incineration at licensed biomedical waste facilities. This ensures zero leaching into the environment and breaks the cycle of resistance.',
    about_you_title: 'Your Role as an AMR Guardian',
    about_you_body: 'Every citizen who brings unused medications to a SafeDrop point becomes a guardian against AMR. By scanning, reporting, and safely disposing, you directly protect your family, community, and future generations from drug-resistant infections.',
    about_tips_title: 'Safe Disposal Tips',
    about_tip_1: 'Never flush medicines down the toilet or sink — they enter the water supply.',
    about_tip_2: 'Do not throw medicines in regular household dustbins — ragpickers and animals are at risk.',
    about_tip_3: 'Check expiry dates regularly and bring expired medicines to a SafeDrop Pharmacy.',
    about_tip_4: 'Complete your full course of antibiotics — do not save leftover doses.',
    about_tip_5: 'Spread awareness — tell your family and neighbours about safe disposal.',
    about_cta: 'Be the change. Scan. Drop. Protect.',
    about_cta_sub: 'Every strip you safely dispose makes India stronger against AMR.',
    // Takeback
    takeback_title: 'Manual Entry & Take-Back',
    takeback_subtitle: 'Log a medication without scanning',
    drug_name: 'Drug Name',
    quantity: 'Quantity (Strips/Bottles)',
    expiry_date: 'Expiry Date',
    is_antibiotic: 'Is this an antibiotic?',
    choose_centre: 'Choose SafeDrop Centre',
    ill_drop_it_myself: 'I will drop it myself',
    contact_method: 'Contact Method',
    whatsapp: 'WhatsApp',
    call: 'Call',
    none: 'None',
    preferred_date: 'Preferred Drop-off Date',
    submit_request: 'Submit Request',
    request_submitted: 'Request Submitted!',
    points_earned: 'Points Earned',
    already_dropped: 'I already dropped this off',
  },
  mr: {
    app_name: 'AMR-गार्ड',
    tagline: 'सुरक्षित विल्हेवाट, मजबूत राष्ट्र',
    welcome_subtitle: 'तुमची औषधे स्कॅन करा, त्यांचा पर्यावरणीय धोका तपासा, आणि जवळचे SafeDrop फार्मसी शोधा — लॉगिन आवश्यक नाही.',
    select_language: 'भाषा निवडा',
    get_started: 'सुरू करा',
    home: 'होम',
    scan: 'स्कॅन',
    map: 'नकाशा',
    profile: 'गार्डियन',
    takeback: 'टेक-बॅक',
    request_takeback: 'टेक-बॅक विनंती',
    recent_scans: 'अलीकडील स्कॅन',
    quick_actions: 'जलद क्रिया',
    scan_medication: 'स्नॅप आणि रिपोर्ट',
    find_centres: 'SafeDrop नकाशा',
    learn_amr: 'AMR माहिती',
    total_scans: 'एकूण स्कॅन',
    antibiotics_found: 'प्रतिजैविके सापडली',
    disposed_safely: 'सुरक्षित विल्हेवाट',
    offline_banner: 'तुम्ही ऑफलाइन आहात. कनेक्शन आल्यावर स्कॅन सिंक होतील.',
    camera_permission: 'औषधे स्कॅन करण्यासाठी कॅमेरा परवानगी आवश्यक आहे.',
    capture: 'कॅप्चर',
    analyzing: 'औषध विश्लेषण करत आहे...',
    result_title: 'विश्लेषण निकाल',
    drug_detected: 'शोधले',
    confidence: 'आत्मविश्वास',
    expiry: 'कालबाह्यता',
    disposal_advice: 'विल्हेवाट शिफारस',
    find_nearest: 'जवळचे SafeDrop फार्मसी शोधा',
    scan_another: 'दुसरे स्कॅन करा',
    saved_offline: 'ऑफलाइन सेव्ह केले. कनेक्शन आल्यावर सिंक होईल.',
    nearest_centres: 'जवळची SafeDrop फार्मसी',
    distance: 'अंतर',
    accepts: 'स्वीकारते',
    get_directions: 'दिशा मिळवा',
    your_location: 'तुमचे ठिकाण',
    loading_map: 'नकाशा लोड होत आहे...',
    locating: 'तुमचे ठिकाण शोधत आहे...',
    guardian_level: 'गार्डियन स्तर',
    eco_hazard: 'इको-हॅझर्ड स्कोर',
    eco_hazard_info: 'पर्यावरणीय प्रभाव',
    hazard_high: 'उच्च धोका',
    hazard_medium: 'मध्यम धोका',
    hazard_low: 'कमी धोका',
    scout: 'रक्षक',
    sentinel: 'प्रहरी',
    amr_guardian: 'योद्धा',
    maha_guardian: 'महा योद्धा',
    scout_desc: 'पहिली विल्हेवाट नोंदवली',
    sentinel_desc: '५ पट्ट्यांची सुरक्षित विल्हेवाट',
    guardian_desc: 'मासिक विल्हेवाट + ३ रेफरल',
    tier_locked: 'लॉक',
    tier_unlocked: 'प्राप्त',
    leaderboard: 'महा-लीडरबोर्ड',
    leaderboard_subtitle: 'शहरनिहाय सुरक्षित विल्हेवाट स्पर्धा',
    disposals: 'विल्हेवाट',
    guardians: 'गार्डियन',
    knowledge_capsules: 'माहिती कॅप्सूल',
    knowledge_what_title: 'AMR म्हणजे काय?',
    knowledge_what_body: 'प्रतिजैविक प्रतिरोध (AMR) तेव्हा होतो जेव्हा जीवाणू प्रतिजैविकांचा प्रतिकार करण्यासाठी विकसित होतात. प्रतिजैविकांची अयोग्य विल्हेवाट ही प्रक्रिया गतिमान करते.',
    knowledge_why_title: 'सुरक्षित विल्हेवाट का?',
    knowledge_why_body: 'प्रतिजैविके पाण्यात गेल्यास सुपरबग तयार होतात. SafeDrop फार्मसी योग्य भस्मीकरण सुनिश्चित करतात.',
    knowledge_how_title: 'तुम्ही कसे मदत करता',
    knowledge_how_body: 'तुम्ही SafeDrop फार्मसीत आणलेली प्रत्येक पट्टी दूषणाचा एक कमी स्रोत आहे.',
    stats: 'तुमचा प्रभाव',
    no_scans_yet: 'अजून स्कॅन नाही. सुरू करण्यासाठी "स्कॅन" वर टॅप करा!',
    antibiotic: 'प्रतिजैविक',
    general: 'सामान्य',
    safe_drop_pharmacy: 'SafeDrop फार्मसी',
    govt_health_center: 'सरकारी आरोग्य केंद्र',
    device_token: 'डिव्हाइस टोकन',
    device_token_info: 'अनामित ID — लॉगिन आवश्यक नाही',
    qr_code: 'विल्हेवाट QR कोड',
    qr_code_info: 'विल्हेवाट सत्यापित करण्यासाठी SafeDrop फार्मसीमध्ये दाखवा',
    points: 'पॉइंट्स',
    points_earned_today: 'आज मिळवलेले पॉइंट्स',
    redeem_points: 'पॉइंट्स रिडीम करा',
    badges: 'बॅजेस',
    rewards_wallet: 'रिवॉर्ड्स वॉलेट',
    transaction_history: 'व्यवहार इतिहास',
    report_disposal: 'विल्हेवाट नोंदवा',
    about: 'माहिती',
    about_title: 'सुरक्षित विल्हेवाट का?',
    about_subtitle: 'भारतातील AMR संकट समजून घेणे',
    about_hero_title: 'भारत एका शांत आरोग्य संकटाला तोंड देत आहे',
    about_hero_body: 'भारत जगातील सर्वात मोठ्या प्रतिजैविक वापरकर्त्यांपैकी एक आहे. जेव्हा न वापरलेली किंवा कालबाह्य प्रतिजैविके शौचालयात फ्लश केली जातात किंवा कचऱ्यात टाकली जातात, तेव्हा ती आमच्या नद्या, माती आणि भूजलात प्रवेश करतात.',
    about_amr_title: 'प्रतिजैविक प्रतिरोध (AMR) म्हणजे काय?',
    about_amr_body: 'AMR तेव्हा होतो जेव्हा जीवाणू, विषाणू आणि बुरशी त्यांना मारण्यासाठी तयार केलेल्या औषधांचा प्रतिकार करण्यासाठी विकसित होतात.',
    about_why_title: 'अयोग्य विल्हेवाट का महत्त्वाची आहे?',
    about_why_body: 'जेव्हा प्रतिजैविके घरगुती कचऱ्यातून पाण्यात प्रवेश करतात, तेव्हा ती सुपरबग तयार करतात. भारतीय नद्यांच्या 80% चाचण्यांमध्ये प्रतिजैविक अवशेष आढळले.',
    about_env_title: 'पर्यावरणीय प्रभाव',
    about_env_body: 'औषधी प्रदूषणामुळे जलचर परिसंस्था प्रभावित होतात, पिण्याच्या पाण्याचे स्रोत दूषित होतात.',
    about_how_title: 'SafeDrop फार्मसी कसे काम करतात',
    about_how_body: 'SafeDrop फार्मसी आणि सरकारी आरोग्य केंद्रे न वापरलेली औषधे गोळा करतात आणि योग्य भस्मीकरणासाठी पाठवतात.',
    about_you_title: 'AMR गार्डियन म्हणून तुमची भूमिका',
    about_you_body: 'SafeDrop पॉइंटवर न वापरलेली औषधे आणणारा प्रत्येक नागरिक AMR विरुद्ध रक्षक बनतो.',
    about_tips_title: 'सुरक्षित विल्हेवाट टिप्स',
    about_tip_1: 'कधीही शौचालयात औषधे फ्लश करू नका.',
    about_tip_2: 'सामान्य कचराकुंडीत औषधे टाकू नका.',
    about_tip_3: 'कालबाह्यता तारखा नियमित तपासा.',
    about_tip_4: 'प्रतिजैविकांचा संपूर्ण कोर्स पूर्ण करा.',
    about_tip_5: 'जागरूकता पसरवा.',
    about_cta: 'बदल घडवा. स्कॅन करा. ड्रॉप करा. रक्षण करा.',
    about_cta_sub: 'तुम्ही सुरक्षितपणे विल्हेवाट लावलेली प्रत्येक पट्टी भारताला AMR विरुद्ध मजबूत करते.',
    takeback_title: 'मॅन्युअल एंट्री',
    takeback_subtitle: 'औषधाची सुरक्षितपणे विल्हेवाट लावा',
    drug_name: 'औषधाचे नाव',
    quantity: 'प्रमाण',
    expiry_date: 'कालबाह्यता तारीख',
    is_antibiotic: 'हे प्रतिजैविक आहे का?',
    choose_centre: 'SafeDrop केंद्र निवडा',
    ill_drop_it_myself: 'मी स्वतः ते टाकेन',
    contact_method: 'संपर्क पद्धत',
    whatsapp: 'WhatsApp',
    call: 'कॉल',
    none: 'काहीही नाही',
    preferred_date: 'पसंतीची तारीख',
    submit_request: 'विनंती सबमिट करा',
    request_submitted: 'विनंती सबमिट केली!',
    points_earned: 'मिळवलेले पॉइंट्स',
    already_dropped: 'मी आधीच विल्हेवाट लावली आहे',
  },
  hi: {
    app_name: 'AMR-गार्ड',
    tagline: 'सुरक्षित निपटान, मजबूत राष्ट्र',
    welcome_subtitle: 'अपनी दवाओं को स्कैन करें, उनके पर्यावरणीय खतरे की जांच करें, और निकटतम SafeDrop फार्मेसी खोजें — कोई लॉगिन आवश्यक नहीं।',
    select_language: 'भाषा चुनें',
    get_started: 'शुरू करें',
    home: 'होम',
    scan: 'स्कैन',
    map: 'नक्शा',
    profile: 'गार्डियन',
    takeback: 'टेक-बैक',
    request_takeback: 'टेक-बैक अनुरोध',
    recent_scans: 'हाल के स्कैन',
    quick_actions: 'त्वरित क्रियाएं',
    scan_medication: 'स्नैप और रिपोर्ट',
    find_centres: 'SafeDrop नक्शा',
    learn_amr: 'AMR ज्ञान',
    total_scans: 'कुल स्कैन',
    antibiotics_found: 'एंटीबायोटिक्स मिले',
    disposed_safely: 'सुरक्षित निपटान',
    offline_banner: 'आप ऑफलाइन हैं। कनेक्शन आने पर स्कैन सिंक हो जाएंगे।',
    camera_permission: 'दवाओं को स्कैन करने के लिए कैमरा अनुमति आवश्यक है।',
    capture: 'कैप्चर',
    analyzing: 'दवा का विश्लेषण हो रहा है...',
    result_title: 'विश्लेषण परिणाम',
    drug_detected: 'पता चला',
    confidence: 'आत्मविश्वास',
    expiry: 'समाप्ति स्थिति',
    disposal_advice: 'निपटान सलाह',
    find_nearest: 'निकटतम SafeDrop फार्मेसी खोजें',
    scan_another: 'दूसरा स्कैन करें',
    saved_offline: 'ऑफ़लाइन सहेजा गया। कनेक्शन आने पर सिंक होगा।',
    nearest_centres: 'आसपास SafeDrop फार्मेसी',
    distance: 'दूरी',
    accepts: 'स्वीकार करता है',
    get_directions: 'दिशा-निर्देश प्राप्त करें',
    your_location: 'आपका स्थान',
    loading_map: 'नक्शा लोड हो रहा है...',
    locating: 'आपका स्थान खोज रहा है...',
    guardian_level: 'गार्डियन स्तर',
    eco_hazard: 'इको-हज़ार्ड स्कोर',
    eco_hazard_info: 'पर्यावरणीय प्रभाव',
    hazard_high: 'उच्च जोखिम',
    hazard_medium: 'मध्यम जोखिम',
    hazard_low: 'कम जोखिम',
    scout: 'रक्षक',
    sentinel: 'प्रहरी',
    amr_guardian: 'योद्धा',
    maha_guardian: 'महा योद्धा',
    scout_desc: 'पहला निपटान रिपोर्ट किया गया',
    sentinel_desc: '5 स्ट्रिप्स सुरक्षित रूप से निपटाए गए',
    guardian_desc: 'लगातार मासिक निपटान + 3 रेफरल',
    tier_locked: 'लॉक',
    tier_unlocked: 'प्राप्त',
    leaderboard: 'महा-लीडरबोर्ड',
    leaderboard_subtitle: 'शहर-वार सुरक्षित निपटान प्रतियोगिता',
    disposals: 'निपटान',
    guardians: 'गार्डियन',
    knowledge_capsules: 'ज्ञान कैप्सूल',
    knowledge_what_title: 'AMR क्या है?',
    knowledge_what_body: 'एंटीमाइक्रोबियल रेजिस्टेंस (AMR) तब होता है जब बैक्टीरिया एंटीबायोटिक्स का विरोध करने के लिए विकसित होते हैं। एंटीबायोटिक्स का अनुचित निपटान इस प्रक्रिया को गति देता है।',
    knowledge_why_title: 'सुरक्षित निपटान क्यों?',
    knowledge_why_body: 'जब एंटीबायोटिक्स पानी की व्यवस्था में प्रवेश करते हैं, तो वे सुपरबग बनाते हैं। SafeDrop फार्मेसी उचित भस्मीकरण सुनिश्चित करती है।',
    knowledge_how_title: 'आप कैसे मदद करते हैं',
    knowledge_how_body: 'हर स्ट्रिप जो आप SafeDrop फार्मेसी में लाते हैं, प्रदूषण का एक कम स्रोत है।',
    stats: 'आपका प्रभाव',
    no_scans_yet: 'अभी तक कोई स्कैन नहीं। शुरू करने के लिए "स्कैन" पर टैप करें!',
    antibiotic: 'एंटीबायोटिक',
    general: 'सामान्य',
    safe_drop_pharmacy: 'SafeDrop फार्मेसी',
    govt_health_center: 'सरकारी स्वास्थ्य केंद्र',
    device_token: 'डिवाइस टोकन',
    device_token_info: 'गुमनाम आईडी — कोई लॉगिन आवश्यक नहीं',
    qr_code: 'निपटान क्यूआर कोड',
    qr_code_info: 'अपना निपटान सत्यापित करने के लिए इसे SafeDrop फार्मेसी में दिखाएं',
    points: 'पॉइंट्स',
    points_earned_today: 'आज अर्जित अंक',
    redeem_points: 'अंक भुनाएं',
    badges: 'बैज',
    rewards_wallet: 'रिवॉर्ड्स वॉलेट',
    transaction_history: 'लेनदेन इतिहास',
    report_disposal: 'निपटान रिपोर्ट करें',
    about: 'के बारे में',
    about_title: 'सुरक्षित निपटान क्यों?',
    about_subtitle: 'भारत में AMR संकट को समझना',
    about_hero_title: 'भारत एक मूक स्वास्थ्य संकट का सामना कर रहा है',
    about_hero_body: 'भारत दुनिया में एंटीबायोटिक्स के सबसे बड़े उपभोक्ताओं में से एक है। जब अप्रयुक्त या समाप्त एंटीबायोटिक्स फ्लश किए जाते हैं या कूड़ेदान में फेंके जाते हैं, तो वे हमारी नदियों और मिट्टी में प्रवेश करते हैं।',
    about_amr_title: 'एंटीमाइक्रोबियल रेजिस्टेंस (AMR) क्या है?',
    about_amr_body: 'AMR तब होता है जब बैक्टीरिया, वायरस और कवक उन्हें मारने के लिए बनाई गई दवाओं का विरोध करने के लिए विकसित होते हैं।',
    about_why_title: 'अनुचित निपटान क्यों मायने रखता है?',
    about_why_body: 'जब एंटीबायोटिक्स घरेलू कचरे के माध्यम से जल निकायों में प्रवेश करते हैं, तो वे सुपरबग बनाते हैं।',
    about_env_title: 'पर्यावरणीय प्रभाव',
    about_env_body: 'दवा प्रदूषण जलीय पारिस्थितिक तंत्र को प्रभावित करता है।',
    about_how_title: 'SafeDrop फार्मेसी कैसे काम करती हैं',
    about_how_body: 'SafeDrop फार्मेसी और सरकारी स्वास्थ्य केंद्र अप्रयुक्त दवाएं एकत्र करते हैं और उचित भस्मीकरण के लिए भेजते हैं।',
    about_you_title: 'AMR गार्डियन के रूप में आपकी भूमिका',
    about_you_body: 'प्रत्येक नागरिक जो SafeDrop बिंदु पर अप्रयुक्त दवाएं लाता है, वह AMR के खिलाफ रक्षक बन जाता है।',
    about_tips_title: 'सुरक्षित निपटान टिप्स',
    about_tip_1: 'कभी भी शौचालय में दवाएं फ्लश न करें।',
    about_tip_2: 'सामान्य कूड़ेदान में दवाएं न फेंकें।',
    about_tip_3: 'नियमित रूप से समाप्ति तिथियों की जांच करें।',
    about_tip_4: 'अपना पूरा एंटीबायोटिक कोर्स पूरा करें।',
    about_tip_5: 'जागरूकता फैलाएं।',
    about_cta: 'बदलाव बनें। स्कैन करें। ड्रॉप करें। रक्षा करें।',
    about_cta_sub: 'हर स्ट्रिप जिसका आप सुरक्षित रूप से निपटान करते हैं, भारत को AMR के खिलाफ मजबूत बनाता है।',
    takeback_title: 'मैन्युअल टेक-बैक',
    takeback_subtitle: 'दवा का सुरक्षित रूप से निपटान करें',
    drug_name: 'दवा का नाम',
    quantity: 'मात्रा',
    expiry_date: 'समाप्ति तिथि',
    is_antibiotic: 'क्या यह एंटीबायोटिक है?',
    choose_centre: 'SafeDrop केंद्र चुनें',
    ill_drop_it_myself: 'मैं इसे स्वयं छोड़ दूंगा',
    contact_method: 'संपर्क विधि',
    whatsapp: 'व्हाट्सएप',
    call: 'कॉल',
    none: 'कोई नहीं',
    preferred_date: 'पसंदीदा तिथि',
    submit_request: 'अनुरोध सबमिट करें',
    request_submitted: 'अनुरोध सबमिट किया गया!',
    points_earned: 'अर्जित अंक',
    already_dropped: 'मैंने पहले ही इसे छोड़ दिया है',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('amr-guard-lang') || 'en');
  useEffect(() => { localStorage.setItem('amr-guard-lang', lang); }, [lang]);
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
